//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 06:30:20 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.batch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentoReferencia", propOrder = {
        "indicador",
        "tipoDocumentoReferencia",
        "numeroDocumentoReferencia"
})
public class
        EDocumentoReferenciaCliente implements Cloneable {

    @XmlElement(required = true)
    protected String indicador;
    @XmlElement(required = true)
    protected String tipoDocumentoReferencia;
    @XmlElement(required = true)
    protected String numeroDocumentoReferencia;

    public String getIndicador() {
        return indicador;
    }

    public void setIndicador(String indicador) {
        this.indicador = indicador;
    }

    public String getTipoDocumentoReferencia() {
        return tipoDocumentoReferencia;
    }

    public void setTipoDocumentoReferencia(String tipoDocumentoReferencia) {
        this.tipoDocumentoReferencia = tipoDocumentoReferencia;
    }

    public String getNumeroDocumentoReferencia() {
        return numeroDocumentoReferencia;
    }

    public void setNumeroDocumentoReferencia(String numeroDocumentoReferencia) {
        this.numeroDocumentoReferencia = numeroDocumentoReferencia;
    }
}
