package pe.gob.sunat.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-11-14T08:29:59.856-05:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://service.sunat.gob.pe", name = "billService")
//@XmlSeeAlso({ObjectFactory.class})
public interface BillServiceSunatInterface {

    @WebMethod(action = "urn:sendBill")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendBillResponse")
    @WebResult(name = "applicationResponse", targetNamespace = "")
    public byte[] sendBill(
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        javax.activation.DataHandler contentFile,
        //byte[] contentFile,
        @WebParam(name = "partyType", targetNamespace = "")
        java.lang.String partyType
    );

    @WebMethod(action = "urn:sendSummary")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendSummaryResponse")
    @WebResult(name = "ticket", targetNamespace = "")
    public java.lang.String sendSummary(
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        javax.activation.DataHandler contentFile,
        @WebParam(name = "partyType", targetNamespace = "")
        java.lang.String partyType
    );

    @WebMethod(action = "urn:sendPack")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendPack")
    @ResponseWrapper(localName = "sendPackResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendPackResponse")
    @WebResult(name = "ticket", targetNamespace = "")
    public java.lang.String sendPack(
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        javax.activation.DataHandler contentFile,
        //byte[] contentFile,
        @WebParam(name = "partyType", targetNamespace = "")
        java.lang.String partyType
    );

    @WebMethod(action = "urn:getStatus")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.GetStatusResponse")
    @WebResult(name = "status", targetNamespace = "")
    public pe.gob.sunat.service.StatusResponse getStatus(
        @WebParam(name = "ticket", targetNamespace = "")
        java.lang.String ticket
    );
    
    @WebMethod(action = "urn:getStatusAR")
    @RequestWrapper(localName = "getStatusAR", targetNamespace = "http://service.sunat.gob.pe/", className = "pe.gob.sunat.service.GetStatusAR")
    @ResponseWrapper(localName = "getStatusResponseAR", targetNamespace = "http://service.sunat.gob.pe/", className = "pe.gob.sunat.service.GetStatusResponseAR")
    @WebResult(name = "status", targetNamespace = "")
    public pe.gob.sunat.service.StatusResponseAR getStatusAR(            
            @WebParam(name = "rucComprobante", targetNamespace = "")
            java.lang.String rucComprobante,
            @WebParam(name = "tipoComprobante", targetNamespace = "")
            java.lang.String tipoComprobante,            
            @WebParam(name = "serieComprobante", targetNamespace = "")
            java.lang.String serieComprobante,
            @WebParam(name = "numeroComprobante", targetNamespace = "")
            java.lang.String numeroComprobante
    );
}
