//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 03:06:08 PM COT 
//

@XmlSchema(
        namespace = MyNamespacePrefixMapper.URI
        , elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
        , attributeFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
        )
package oasis.names.specification.ubl.schema.xsd.invoice_2;

import javax.xml.bind.annotation.XmlSchema;

import com.axteroid.ose.server.ubl20.gateway.request.MyNamespacePrefixMapper;