//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 03:06:42 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:sunat:names:specification:ubl:peru:schema:xsd:SunatAggregateComponents-1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sunat.names.specification.ubl.peru.schema.xsd.sunataggregatecomponents_1;
