//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 03:06:42 PM COT 
//

package sunat.names.specification.ubl.peru.schema.xsd.sunataggregatecomponents_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.CodeType;

/**
 * User: HNA
 * Date: 09/12/15
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SunatPerceptionSystemCodeType")
public class SunatPerceptionSystemCodeType
    extends CodeType
{


}
