//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 05:00:40 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.response;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.axteroid.ose.server.ubl20.adapter.AdapterCDATA;
import com.axteroid.ose.server.ubl20.adapter.DateAdapter;

import java.util.Date;
import java.util.List;


/**
 * <p>Java class for documentResult complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="documentResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="barCodeFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="declareTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="documentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="documentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hashCode" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="messages" type="{}message" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pdfFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="signTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xmlFileSign" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adicionales", propOrder = {
        "adicionalList"
})
public class AdicionalGroup {

    @XmlElement(name = "adicional", nillable = true)
    protected List<Adicional> adicionalList;

    public AdicionalGroup(List<Adicional> adicionalList) {
        this.adicionalList = adicionalList;
    }

    public AdicionalGroup() {
    }

    public List<Adicional> getAdicionalList() {
        return adicionalList;
    }

    public void setAdicionalList(List<Adicional> adicionalList) {
        this.adicionalList = adicionalList;
    }
}
