//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 05:00:40 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.response;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.axteroid.ose.server.ubl20.adapter.AdapterCDATA;
import com.axteroid.ose.server.ubl20.adapter.DateAdapter;

import java.util.Date;
import java.util.List;


/**
 * <p>Java class for documentResult complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="documentResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="barCodeFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="declareTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="documentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="documentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hashCode" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="messages" type="{}message" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pdfFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="signTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xmlFileSign" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentResult", propOrder = {
        "typeDocument",
        "idDocument",
        "status",
        "statusDocument",
        "statusSunat",
        "signTime",
        "declareTime",
        "responseTime",
        "signatureValue",
        "emisionTime",
        "message",
        "messageSunat",
        "messages",
        "hashCode",
        "barCodeFileUrl",
        "pdfFileUrl",
        "xmlFileSignUrl",
        "xmlFileSunatUrl",
        "tipoDocumentoEmisor",
        "numeroDocumentoEmisor",
        "tipoDocumentoAdquiriente",
        "numeroDocumentoAdquiriente",
        "razonSocialAdquiriente",
        "razonSocialEmisor",
        "adicionales",
        "item"
})
@XmlRootElement
public class DocumentResult {

    @XmlJavaTypeAdapter(DateAdapter.class)
    protected Date declareTime;
    @XmlJavaTypeAdapter(DateAdapter.class)
    protected Date responseTime;
    protected String signatureValue;
    protected String idDocument;
    protected String typeDocument;
    @XmlElement(name = "messages", nillable = true)
    protected List<Message> messages;
    @XmlElement(name = "adicionales", nillable = true)
    protected AdicionalGroup adicionales;
    @XmlElement(name = "item", nillable = true)
    protected List<DocumentItemResult> item;
    @XmlJavaTypeAdapter(DateAdapter.class)
    protected Date signTime;
    protected String status;
    protected String statusDocument;
    protected String statusSunat;
    @XmlJavaTypeAdapter(AdapterCDATA.class)
    private String message;
    @XmlJavaTypeAdapter(AdapterCDATA.class)
    private String messageSunat;
    protected String barCodeFileUrl;
    protected String pdfFileUrl;
    protected String xmlFileSignUrl;
    protected String xmlFileSunatUrl;
    @XmlJavaTypeAdapter(DateAdapter.class)
    private Date emisionTime;

    protected String tipoDocumentoEmisor;
    protected String numeroDocumentoEmisor;

    private String tipoDocumentoAdquiriente;
    private String numeroDocumentoAdquiriente;
    @XmlJavaTypeAdapter(AdapterCDATA.class)
    private String razonSocialAdquiriente;
    @XmlJavaTypeAdapter(AdapterCDATA.class)
    private String razonSocialEmisor;
    protected String hashCode;

    public Date getDeclareTime() {
        return declareTime;
    }

    public void setDeclareTime(Date declareTime) {
        this.declareTime = declareTime;
    }

    public String getIdDocument() {
        return idDocument;
    }

    public void setIdDocument(String idDocument) {
        this.idDocument = idDocument;
    }

    public String getTypeDocument() {
        return typeDocument;
    }

    public void setTypeDocument(String typeDocument) {
        this.typeDocument = typeDocument;
    }

    public String getHashCode() {
        return hashCode;
    }

    public void setHashCode(String hashCode) {
        this.hashCode = hashCode;
    }

    public List<Message> getMessages() {
        return messages;
    }

    public void setMessages(List<Message> messages) {
        this.messages = messages;
    }


    public Date getSignTime() {
        return signTime;
    }

    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DocumentResult that = (DocumentResult) o;

        if (idDocument != null ? !idDocument.equals(that.idDocument) : that.idDocument != null) return false;
        if (typeDocument != null ? !typeDocument.equals(that.typeDocument) : that.typeDocument != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = idDocument != null ? idDocument.hashCode() : 0;
        result = 31 * result + (typeDocument != null ? typeDocument.hashCode() : 0);
        return result;
    }

    public String getXmlFileSignUrl() {
        return xmlFileSignUrl;
    }

    public void setXmlFileSignUrl(String xmlFileSignUrl) {
        this.xmlFileSignUrl = xmlFileSignUrl;
    }

    public String getPdfFileUrl() {
        return pdfFileUrl;
    }

    public void setPdfFileUrl(String pdfFileUrl) {
        this.pdfFileUrl = pdfFileUrl;
    }

    public String getBarCodeFileUrl() {
        return barCodeFileUrl;
    }

    public void setBarCodeFileUrl(String barCodeFileUrl) {
        this.barCodeFileUrl = barCodeFileUrl;
    }

    public String getStatusSunat() {
        return statusSunat;
    }

    public void setStatusSunat(String statusSunat) {
        this.statusSunat = statusSunat;
    }

    public String getMessageSunat() {
        return messageSunat;
    }

    public void setMessageSunat(String messageSunat) {
        this.messageSunat = messageSunat;
    }



    public void cleandUrl() {
        setPdfFileUrl(null);
        setXmlFileSignUrl(null);
        setBarCodeFileUrl(null);
    }

    public void cleandSummaryUrl() {
        setPdfFileUrl(null);
        setBarCodeFileUrl(null);
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Date getEmisionTime() {
        return emisionTime;
    }

    public void setEmisionTime(Date emisionTime) {
        this.emisionTime = emisionTime;
    }

    public String getTipoDocumentoAdquiriente() {
        return tipoDocumentoAdquiriente;
    }

    public void setTipoDocumentoAdquiriente(String tipoDocumentoAdquiriente) {
        this.tipoDocumentoAdquiriente = tipoDocumentoAdquiriente;
    }

    public String getNumeroDocumentoAdquiriente() {
        return numeroDocumentoAdquiriente;
    }

    public void setNumeroDocumentoAdquiriente(String numeroDocumentoAdquiriente) {
        this.numeroDocumentoAdquiriente = numeroDocumentoAdquiriente;
    }

    public String getRazonSocialAdquiriente() {
        return razonSocialAdquiriente;
    }

    public void setRazonSocialAdquiriente(String razonSocialAdquiriente) {
        this.razonSocialAdquiriente = razonSocialAdquiriente;
    }

    public String getRazonSocialEmisor() {
        return razonSocialEmisor;
    }

    public void setRazonSocialEmisor(String razonSocialEmisor) {
        this.razonSocialEmisor = razonSocialEmisor;
    }

    public String getStatusDocument() {
        return statusDocument;
    }

    public void setStatusDocument(String statusDocument) {
        this.statusDocument = statusDocument;
    }

    @Override
    public String toString() {
        return "DocumentResult{" +
                "declareTime=" + declareTime +
                ", responseTime=" + responseTime + '\''+
                ", idDocument='" + idDocument + '\'' +
                ", typeDocument='" + typeDocument + '\'' +
                ", messages=" + messages +
                ", signTime=" + signTime +
                ", status='" + status + '\'' +
                ", statusDocument='" + statusDocument + '\'' +
                ", statusSunat='" + statusSunat + '\'' +
                ", message='" + message + '\'' +
                ", messageSunat='" + messageSunat + '\'' +
                ", barCodeFileUrl='" + barCodeFileUrl + '\'' +
                ", pdfFileUrl='" + pdfFileUrl + '\'' +
                ", xmlFileSignUrl='" + xmlFileSignUrl + '\'' +
                ", emisionTime=" + emisionTime +
                ", tipoDocumentoAdquiriente='" + tipoDocumentoAdquiriente + '\'' +
                ", numeroDocumentoAdquiriente='" + numeroDocumentoAdquiriente + '\'' +
                ", razonSocialAdquiriente='" + razonSocialAdquiriente + '\'' +
                ", razonSocialEmisor='" + razonSocialEmisor + '\'' +
                ", hashCode='" + hashCode + '\'' +
                '}';
    }

    public String getTipoDocumentoEmisor() {
        return tipoDocumentoEmisor;
    }

    public void setTipoDocumentoEmisor(String tipoDocumentoEmisor) {
        this.tipoDocumentoEmisor = tipoDocumentoEmisor;
    }

    public String getNumeroDocumentoEmisor() {
        return numeroDocumentoEmisor;
    }

    public void setNumeroDocumentoEmisor(String numeroDocumentoEmisor) {
        this.numeroDocumentoEmisor = numeroDocumentoEmisor;
    }

    public String getSignatureValue() {
        return signatureValue;
    }

    public void setSignatureValue(String signatureValue) {
        this.signatureValue = signatureValue;
    }

    public AdicionalGroup getAdicionales() {
        return adicionales;
    }

    public void setAdicionales(AdicionalGroup adicionales) {
        this.adicionales = adicionales;
    }

    public List<DocumentItemResult> getItem() {
        return item;
    }

    public void setItem(List<DocumentItemResult> item) {
        this.item = item;
    }

    public String getXmlFileSunatUrl() {
        return xmlFileSunatUrl;
    }

    public void setXmlFileSunatUrl(String xmlFileSunatUrl) {
        this.xmlFileSunatUrl = xmlFileSunatUrl;
    }

	public Date getResponseTime() {
		return responseTime;
	}

	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}
}
