//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 05:00:40 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ebizResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ebizResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="genericInvokeResponse" type="{}genericInvokeResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ebizResponse", propOrder = {
    "genericInvokeResponse"
})
@XmlRootElement
public class EbizResponse {

    protected GenericInvokeResponse genericInvokeResponse;

    /**
     * Gets the value of the genericInvokeResponse property.
     * 
     * @return
     *     possible object is
     *     {@link GenericInvokeResponse }
     *     
     */
    public GenericInvokeResponse getGenericInvokeResponse() {
        return genericInvokeResponse;
    }

    public CommonResponse getCommonResponse(){
        return getGenericInvokeResponse().getCommonResponse();
    }

    public SummaryResult getSummaryResult(){
        return getGenericInvokeResponse().getCommonResponse().getSummaryResult();
    }

    /**
     * Sets the value of the genericInvokeResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericInvokeResponse }
     *     
     */
    public void setGenericInvokeResponse(GenericInvokeResponse value) {
        this.genericInvokeResponse = value;
    }

}
