//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 05:00:40 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for genericInvokeResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="genericInvokeResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commonResponse" type="{}commonResponse" minOccurs="0"/>
 *         &lt;element name="xmlResult" type="{}xmlResult" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "genericInvokeResponse", propOrder = {
    "commonResponse",
    "xmlResult"
})
public class GenericInvokeResponse {

    protected CommonResponse commonResponse;
    protected XmlResult xmlResult;

    /**
     * Gets the value of the commonResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CommonResponse }
     *     
     */
    public CommonResponse getCommonResponse() {
        return commonResponse;
    }

    /**
     * Sets the value of the commonResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonResponse }
     *     
     */
    public void setCommonResponse(CommonResponse value) {
        this.commonResponse = value;
    }

    /**
     * Gets the value of the xmlResult property.
     * 
     * @return
     *     possible object is
     *     {@link XmlResult }
     *     
     */
    public XmlResult getXmlResult() {
        return xmlResult;
    }

    /**
     * Sets the value of the xmlResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlResult }
     *     
     */
    public void setXmlResult(XmlResult value) {
        this.xmlResult = value;
    }

}
