//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 05:00:40 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.axteroid.ose.server.ubl20.adapter.AdapterCDATA;


/**
 * <p>Java class for message complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="descriptionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "message", propOrder = {
        "codeStatus",
        "descriptionStatus",
        "codeDetail",
        "descriptionDetail",
        "listDetail"
})
public class Message {
    protected String codeStatus;


    @XmlJavaTypeAdapter(AdapterCDATA.class)
    protected String descriptionStatus;

    protected String codeDetail;

    @XmlJavaTypeAdapter(AdapterCDATA.class)
    protected String descriptionDetail;
    protected String listDetail;

    public Message() {
    }

    public Message(String codeStatus, String descriptionStatus, String descriptionDetail) {
        this.codeStatus = codeStatus;
        this.descriptionStatus = descriptionStatus;
        this.descriptionDetail = descriptionDetail;
    }

    public String getCodeStatus() {
        return codeStatus;
    }

    public void setCodeStatus(String codeStatus) {
        this.codeStatus = codeStatus;
    }

    public String getDescriptionStatus() {
        return descriptionStatus;
    }

    public void setDescriptionStatus(String descriptionStatus) {
        this.descriptionStatus = descriptionStatus;
    }

    public String getCodeDetail() {
        return codeDetail;
    }

    public void setCodeDetail(String codeDetail) {
        this.codeDetail = codeDetail;
    }

    public String getDescriptionDetail() {
        return descriptionDetail;
    }

    public void setDescriptionDetail(String descriptionDetail) {
        this.descriptionDetail = descriptionDetail;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Message message = (Message) o;

        if (codeDetail != null ? !codeDetail.equals(message.codeDetail) : message.codeDetail != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return codeDetail != null ? codeDetail.hashCode() : 0;
    }

    @Override
    public String toString() {
        return "Message{" +
                "codeStatus='" + codeStatus + '\'' +
                ", descriptionStatus='" + descriptionStatus + '\'' +
                ", codeDetail='" + codeDetail + '\'' +
                ", descriptionStatus='" + descriptionDetail + '\'' +
                ", listDetail='" + listDetail + '\'' +
                '}';
    }

    public String getListDetail() {
        return listDetail;
    }

    public void setListDetail(String listDetail) {
        this.listDetail = listDetail;
    }
}
