//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 03:06:08 PM COT 
//
package sunat.names.specification.ubl.peru.schema.xsd.retention_1;

import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.axteroid.ose.server.ubl20.gateway.request.MyNamespacePrefixMapper;

import oasis.names.specification.ubl.schema.xsd.IRetencionSunat;
import oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.PartyType;
import oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.SignatureType;
import oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.SunatRetentionDocumentReferenceType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.CustomizationIDType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.IDType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.IssueDateType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.NoteType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.PaidAmountType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TotalInvoiceAmountType;
import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.UBLVersionIDType;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.UBLExtensionsType;
import sunat.names.specification.ubl.peru.schema.xsd.sunataggregatecomponents_1.SunatRetentionPercentType;
import sunat.names.specification.ubl.peru.schema.xsd.sunataggregatecomponents_1.SunatRetentionSystemCodeType;


/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Component xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns="urn:sunat:names:specification:ubl:peru:schema:xsd:Retention-1" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:qdt="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2" xmlns:udt="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;ccts:ComponentType&gt;ABIE&lt;/ccts:ComponentType&gt;&lt;ccts:DictionaryEntryName&gt;Retention. Details&lt;/ccts:DictionaryEntryName&gt;&lt;ccts:Definition&gt;The document used to request payment.&lt;/ccts:Definition&gt;&lt;ccts:ObjectClass&gt;Retention&lt;/ccts:ObjectClass&gt;
 *
 * 				&lt;/ccts:Component&gt;
 * </pre>
 * <p/>
 * <p/>
 * <p/>
 * <p>Java class for RetentionType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="RetentionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}UBLVersionID" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueDate"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}RetentionTypeCode" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Note" maxOccurs="unbounded" minOccurs="0"/>


 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2}UBLExtensions" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}Signature" maxOccurs="unbounded" minOccurs="0"/>


 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}SellerSupplierParty" minOccurs="0"/> *         

 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}RetentionLine" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Retention", propOrder = {
		"ublVersionID",
		"customizationID",
		"ublExtensions",
		"signature",
		"id",
		"issueDate",
		"agentParty",
		"receiverParty",
		"sunatRetentionSystemCode",
		"sunatRetentionPercent",
		"note",
		"totalInvoiceAmount",
		"sunatTotalPaid",
		"sunatRetentionDocumentReference"
})
@XmlRootElement(name = "Retention", namespace = MyNamespacePrefixMapper.URI_RETENTION)
public class RetentionType implements IRetencionSunat {

    @XmlElement(name = "UBLVersionID", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected UBLVersionIDType ublVersionID;
    @XmlElement(name = "CustomizationID", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected CustomizationIDType customizationID;
    @XmlElement(name = "UBLExtensions", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")
    protected UBLExtensionsType ublExtensions;
    @XmlElement(name = "Signature", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")
    protected List<SignatureType> signature;    
    @Valid
    @XmlElement(name = "ID",nillable = false,namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected IDType id;
    @XmlElement(name = "IssueDate", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected IssueDateType issueDate;
    @XmlElement(name = "AgentParty", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")
    protected PartyType agentParty;    
    @XmlElement(name = "ReceiverParty", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")
    protected PartyType receiverParty;     
    @XmlElement(name = "SUNATRetentionSystemCode", namespace = MyNamespacePrefixMapper.SAC_URI)
    protected SunatRetentionSystemCodeType sunatRetentionSystemCode;
    @XmlElement(name = "SUNATRetentionPercent", namespace = MyNamespacePrefixMapper.SAC_URI)    
    protected SunatRetentionPercentType sunatRetentionPercent;
    @XmlElement(name = "Note", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected List<NoteType> note;
    @XmlElement(name = "TotalInvoiceAmount", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected TotalInvoiceAmountType totalInvoiceAmount;
    @XmlElement(name = "SUNATTotalPaid", namespace = MyNamespacePrefixMapper.SAC_URI)
    protected PaidAmountType sunatTotalPaid;
    @XmlElement(name = "SUNATRetentionDocumentReference", namespace = MyNamespacePrefixMapper.SAC_URI)
    protected List<SunatRetentionDocumentReferenceType> sunatRetentionDocumentReference;
    
	public UBLVersionIDType getUblVersionID() {
		return ublVersionID;
	}
	public void setUblVersionID(UBLVersionIDType ublVersionID) {
		this.ublVersionID = ublVersionID;
	}
	public CustomizationIDType getCustomizationID() {
		return customizationID;
	}
	public void setCustomizationID(CustomizationIDType customizationID) {
		this.customizationID = customizationID;
	}
	public UBLExtensionsType getUblExtensions() {
		return ublExtensions;
	}
	public void setUblExtensions(UBLExtensionsType ublExtensions) {
		this.ublExtensions = ublExtensions;
	}
    public List<SignatureType> getSignature() {
        if (signature == null) {
            signature = new ArrayList<SignatureType>();
        }
        return this.signature;
    }

    public void insertSignatureType(SignatureType value){
        getSignature().add(value);
    }
	public void setSignature(List<SignatureType> signature) {
		this.signature = signature;
	}
	public IDType getId() {
		return id;
	}
	public void setId(IDType id) {
		this.id = id;
	}
	public IssueDateType getIssueDate() {
		return issueDate;
	}
	public void setIssueDate(IssueDateType issueDate) {
		this.issueDate = issueDate;
	}
	public PartyType getAgentParty() {
		return agentParty;
	}
	public void setAgentParty(PartyType agentParty) {
		this.agentParty = agentParty;
	}
	public PartyType getReceiverParty() {
		return receiverParty;
	}
	public void setReceiverParty(PartyType receiverParty) {
		this.receiverParty = receiverParty;
	}
	public SunatRetentionSystemCodeType getSunatRetentionSystemCode() {
		return sunatRetentionSystemCode;
	}
	public void setSunatRetentionSystemCode(
			SunatRetentionSystemCodeType sunatRetentionSystemCode) {
		this.sunatRetentionSystemCode = sunatRetentionSystemCode;
	}
	public SunatRetentionPercentType getSunatRetentionPercent() {
		return sunatRetentionPercent;
	}
	public void setSunatRetentionPercent(
			SunatRetentionPercentType sunatRetentionPercent) {
		this.sunatRetentionPercent = sunatRetentionPercent;
	}
    public List<NoteType> getNote() {
        if (note == null) {
            note = new ArrayList<NoteType>();
        }
        return this.note;
    }
	public void setNote(List<NoteType> note) {
		this.note = note;
	}
    public void insertNoteType(NoteType value) {
    	this.note.add(value);
    }
	public TotalInvoiceAmountType getTotalInvoiceAmount() {
		return totalInvoiceAmount;
	}
	public void setTotalInvoiceAmount(TotalInvoiceAmountType totalInvoiceAmount) {
		this.totalInvoiceAmount = totalInvoiceAmount;
	}
	public PaidAmountType getSunatTotalPaid() {
		return sunatTotalPaid;
	}
	public void setSunatTotalPaid(PaidAmountType sunatTotalPaid) {
		this.sunatTotalPaid = sunatTotalPaid;
	}
	public List<SunatRetentionDocumentReferenceType> getSunatRetentionDocumentReference() {
		return sunatRetentionDocumentReference;
	}
	public void setSunatRetentionDocumentReference(
			List<SunatRetentionDocumentReferenceType> sunatRetentionDocumentReference) {
		this.sunatRetentionDocumentReference = sunatRetentionDocumentReference;
	}
	public UBLExtensionsType getUBLExtensions() {
		return ublExtensions;
	}
}
