//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 05:00:40 PM COT 
//


package com.axteroid.ose.server.ubl20.ws.response;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.axteroid.ose.server.tools.edocu.EDocumento;
import com.axteroid.ose.server.tools.edocu.EGuiaDocumento;
import com.axteroid.ose.server.tools.edocu.EPercepcionDocumento;
import com.axteroid.ose.server.tools.edocu.EResumenDocumento;
import com.axteroid.ose.server.tools.edocu.ERetencionDocumento;
import com.axteroid.ose.server.tools.edocu.EReversionDocumento;
import com.axteroid.ose.server.tools.edocu.IDocumento;
import com.axteroid.ose.server.ubl20.gateway.response.Message;


/**
 * <p>Java class for documentResult complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="documentResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="barCodeFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="declareTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="documentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="documentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hashCode" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="messages" type="{}message" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pdfFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="signTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xmlFileSign" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public class EDocumentResult implements IDocumento {

    protected Date declareTime;
    protected String idDocument;
    protected String typeDocument;
    protected String hashCode;
    protected String firmaElectronica;
    protected String fileRuta;
    private String rutaAdjunto_1;
    private String rutaAdjunto_2;
    private String rutaAdjunto_3;
    private String rutaAdjunto_4;
    private String rutaAdjunto_5;
    private String nombreAdjunto_1;
    private String nombreAdjunto_2;
    private String nombreAdjunto_3;
    private String nombreAdjunto_4;
    private String nombreAdjunto_5;
    private byte[] adjunto_1;
    private byte[] adjunto_2;
    private byte[] adjunto_3;
    private byte[] adjunto_4;
    private byte[] adjunto_5;

    private String fileName;
    private String message;
    private String messageSunat;

    protected List<Message> messages = new ArrayList<Message>();

    private String tipoDocumentoEmisor;
    private String numeroDocumentoEmisor;
    private BigDecimal totalIgv;
    private BigDecimal totalVenta;
    private Date fechaEmision;
    private String tipoDocumentoAdquiriente;
    private String numeroDocumentoAdquiriente;
    private String razonSocialAdquiriente;
    private String razonSocialEmisor;
    private String correoAdquiriente;
    private String correoEmisor;

    protected Date signTime;
    protected String status;
    protected String statusDocument;
    protected String statusSunat;
    protected String xmlData;
    protected String digestValue;
    protected String signatureValue;
    protected byte[] archivoEnviado;
    protected byte[] archivoRespuesta;
    protected String usuarioSol;
    protected String claveSol;
    protected String codigoBarraFuente;
    protected Date responseTime;

    public EDocumentResult() {
    }

    public String getSerieDocumento() {
        return idDocument.substring(0, idDocument.lastIndexOf('-'));

    }

    public String getNumeroDocumento() {
        return idDocument.substring(idDocument.lastIndexOf('-')+1, idDocument.length());
    }

    public EDocumentResult(IDocumento documento, String estado) {
        setTypeDocument(documento.getTipoDocumento());
        setIdDocument(documento.getIdDocumento());
        setStatus(estado);
    }

    public Date getDeclareTime() {
        return declareTime;
    }

    public void setDeclareTime(Date declareTime) {
        this.declareTime = declareTime;
    }

    public String getIdDocument() {
        return idDocument;
    }

    public void setIdDocument(String idDocument) {
        this.idDocument = idDocument;
    }

    public String getTypeDocument() {
        return typeDocument;
    }

    public void setTypeDocument(String typeDocument) {
        this.typeDocument = typeDocument;
    }

    public String getHashCode() {
        return hashCode;
    }

    public void setHashCode(String hashCode) {
        this.hashCode = hashCode;
    }

    public List<Message> getMessages() {
        return messages;
    }

    public void setMessages(List<Message> messages) {
        this.messages = messages;
    }


    public Date getSignTime() {
        return signTime;
    }

    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        EDocumentResult that = (EDocumentResult) o;

        if (idDocument != null ? !idDocument.equals(that.idDocument) : that.idDocument != null) return false;
        if (typeDocument != null ? !typeDocument.equals(that.typeDocument) : that.typeDocument != null) return false;
        if (status != null ? !status.equals(that.status) : that.status != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = idDocument != null ? idDocument.hashCode() : 0;
        result = 31 * result + (typeDocument != null ? typeDocument.hashCode() : 0);
        result = 31 * result + (status != null ? status.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "EDocumentResult{" +
                "typeDocument='" + typeDocument + '\'' +
                ", idDocument='" + idDocument + '\'' +
                ", status='" + status + '\'' +
                '}';
    }

    public String getNumeroDocumentoEmisor() {
        return numeroDocumentoEmisor;
    }

    public String getTipoDocumentoEmisor() {
        return tipoDocumentoEmisor;
    }

    public String getIdDocumento() {
        return idDocument;
    }

    public String getTipoDocumento() {
        return typeDocument;
    }

    public void populate(IDocumento documento) {
        setTipoDocumentoEmisor(documento.getTipoDocumentoEmisor());
        setNumeroDocumentoEmisor(documento.getNumeroDocumentoEmisor());
        setTipoDocumento(documento.getTipoDocumento());
        setIdDocumento(documento.getIdDocumento());
        if (documento instanceof EDocumento) {
            setTotalIgv(((EDocumento) documento).getTotalIgv());
            setTotalVenta(((EDocumento) documento).getTotalVenta());
            setFechaEmision(((EDocumento) documento).getFechaEmision());
            setTipoDocumentoAdquiriente((documento).getTipoDocumentoAdquiriente());
            setNumeroDocumentoAdquiriente((documento).getNumeroDocumentoAdquiriente());
        }
        if(documento instanceof EResumenDocumento){
            setFechaEmision(((EResumenDocumento) documento).getFechaEmisionComprobante());
        }
        if(documento instanceof EGuiaDocumento){
            setFechaEmision(((EGuiaDocumento) documento).getFechaEmisionGuia());
            setTipoDocumentoAdquiriente((documento).getTipoDocumentoAdquiriente());
            setNumeroDocumentoAdquiriente((documento).getNumeroDocumentoAdquiriente());
        }
        if(documento instanceof ERetencionDocumento){
            setFechaEmision(((ERetencionDocumento) documento).getFechaEmision());
            setTipoDocumentoAdquiriente((documento).getTipoDocumentoAdquiriente());
            setNumeroDocumentoAdquiriente((documento).getNumeroDocumentoAdquiriente());
            setTotalVenta(((ERetencionDocumento) documento).getImporteTotalRetenido());
        }
        if(documento instanceof EPercepcionDocumento){
            setFechaEmision(((EPercepcionDocumento) documento).getFechaEmision());
            setTipoDocumentoAdquiriente((documento).getTipoDocumentoAdquiriente());
            setNumeroDocumentoAdquiriente((documento).getNumeroDocumentoAdquiriente());
            setTotalVenta(((EPercepcionDocumento) documento).getImporteTotalPercibido());
        }
        if(documento instanceof EReversionDocumento){
            setFechaEmision(((EReversionDocumento) documento).getFechaDocumentoRevertido());
        }
    }


    public void setTipoDocumentoEmisor(String tipoDocumentoEmisor) {
        this.tipoDocumentoEmisor = tipoDocumentoEmisor;
    }

    public void setNumeroDocumentoEmisor(String numeroDocumentoEmisor) {
        this.numeroDocumentoEmisor = numeroDocumentoEmisor;
    }

    public void setTipoDocumento(String tipoDocumento) {
        this.typeDocument = tipoDocumento;
    }

    public void setIdDocumento(String idDocumento) {
        this.idDocument = idDocumento;
    }

    public BigDecimal getTotalIgv() {
        return totalIgv;
    }

    public void setTotalIgv(BigDecimal totalIgv) {
        this.totalIgv = totalIgv;
    }

    public BigDecimal getTotalVenta() {
        return totalVenta;
    }

    public void setTotalVenta(BigDecimal totalVenta) {
        this.totalVenta = totalVenta;
    }

    public Date getFechaEmision() {
        return fechaEmision;
    }

    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    public String getTipoDocumentoAdquiriente() {
        return tipoDocumentoAdquiriente;
    }

    public void setTipoDocumentoAdquiriente(String tipoDocumentoAdquiriente) {
        this.tipoDocumentoAdquiriente = tipoDocumentoAdquiriente;
    }

    public String getNumeroDocumentoAdquiriente() {
        return numeroDocumentoAdquiriente;
    }

    public void setNumeroDocumentoAdquiriente(String numeroDocumentoAdquiriente) {
        this.numeroDocumentoAdquiriente = numeroDocumentoAdquiriente;
    }

    public String getEstado() {
        return null;  //Todo implementar
    }

    public String getXmlData() {
        return xmlData;
    }

    public void setXmlData(String xmlData) {
        this.xmlData = xmlData;
    }

    public Date getFechaDocumento() {
        return getFechaEmision();
    }

    public String getCodigoBarraFuente() {
        return codigoBarraFuente;
    }

    public void setCodigoBarraFuente(String codigoBarraFuente) {
        this.codigoBarraFuente = codigoBarraFuente;
    }

    public String getFirmaElectronica() {
        return firmaElectronica;
    }

    public void setFirmaElectronica(String firmaElectronica) {
        this.firmaElectronica = firmaElectronica;
    }

    public String getRazonSocialAdquiriente() {
        return razonSocialAdquiriente;
    }

    public void setRazonSocialAdquiriente(String razonSocialAdquiriente) {
        this.razonSocialAdquiriente = razonSocialAdquiriente;
    }

    public String getCorreoAdquiriente() {
        return correoAdquiriente;
    }

    public void setCorreoAdquiriente(String correoAdquiriente) {
        this.correoAdquiriente = correoAdquiriente;
    }

    public String getCorreoEmisor() {
        return correoEmisor;
    }

    public void setCorreoEmisor(String correoEmisor) {
        this.correoEmisor = correoEmisor;
    }

    public String getUsuarioSol() {
        return usuarioSol;
    }

    public void setUsuarioSol(String usuarioSol) {
        this.usuarioSol = usuarioSol;
    }

    public String getClaveSol() {
        return claveSol;
    }

    public void setClaveSol(String claveSol) {
        this.claveSol = claveSol;
    }

    public String getRutaAdjunto_1() {
        return rutaAdjunto_1;
    }

    public void setRutaAdjunto_1(String rutaAdjunto_1) {
        this.rutaAdjunto_1 = rutaAdjunto_1;
    }

    public String getRutaAdjunto_2() {
        return rutaAdjunto_2;
    }

    public void setRutaAdjunto_2(String rutaAdjunto_2) {
        this.rutaAdjunto_2 = rutaAdjunto_2;
    }

    public String getRutaAdjunto_3() {
        return rutaAdjunto_3;
    }

    public void setRutaAdjunto_3(String rutaAdjunto_3) {
        this.rutaAdjunto_3 = rutaAdjunto_3;
    }

    public String getRutaAdjunto_4() {
        return rutaAdjunto_4;
    }

    public void setRutaAdjunto_4(String rutaAdjunto_4) {
        this.rutaAdjunto_4 = rutaAdjunto_4;
    }

    public String getRutaAdjunto_5() {
        return rutaAdjunto_5;
    }

    public void setRutaAdjunto_5(String rutaAdjunto_5) {
        this.rutaAdjunto_5 = rutaAdjunto_5;
    }


    public String getRazonSocialEmisor() {
        return razonSocialEmisor;
    }

    public void setRazonSocialEmisor(String razonSocialEmisor) {
        this.razonSocialEmisor = razonSocialEmisor;
    }
/*
    public String getFileRuta() {
        return fileRuta;
    }

    public void setFileRuta(String fileRuta) {
        this.fileRuta = fileRuta;
    }*/

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getMessageSunat() {
        return messageSunat;
    }

    public void setMessageSunat(String messageSunat) {
        this.messageSunat = messageSunat;
    }

    public String getStatusDocument() {
        return statusDocument;
    }

    public void setStatusDocument(String statusDocument) {
        this.statusDocument = statusDocument;
    }

    public String getStatusSunat() {
        return statusSunat;
    }

    public void setStatusSunat(String statusSunat) {
        this.statusSunat = statusSunat;
    }

    public boolean isExportacion() {
        return false;  //To change body of implemented methods use File | Settings | File Templates.
    }

    public boolean isNotaDebitoPorPenalidad() {
        return false;
    }

    public String getUrlLink() {
        return "&d1="+getNumeroDocumentoEmisor()+
                "&d3="+getIdDocumento()+
                "&d2="+getTipoDocumento();
    }

    public byte[] getArchivoEnviado() {
        return archivoEnviado;
    }

    public void setArchivoEnviado(byte[] archivoEnviado) {
        this.archivoEnviado = archivoEnviado;
    }

    public byte[] getArchivoRespuesta() {
        return archivoRespuesta;
    }

    public void setArchivoRespuesta(byte[] archivoRespuesta) {
        this.archivoRespuesta = archivoRespuesta;
    }

    public String getDigestValue() {
        return digestValue;
    }

    public void setDigestValue(String digestValue) {
        this.digestValue = digestValue;
    }

    public String getSignatureValue() {
        return signatureValue;
    }

    public void setSignatureValue(String signatureValue) {
        this.signatureValue = signatureValue;
    }

    public String getNombreAdjunto_1() {
        return nombreAdjunto_1;
    }

    public void setNombreAdjunto_1(String nombreAdjunto_1) {
        this.nombreAdjunto_1 = nombreAdjunto_1;
    }

    public String getNombreAdjunto_2() {
        return nombreAdjunto_2;
    }

    public void setNombreAdjunto_2(String nombreAdjunto_2) {
        this.nombreAdjunto_2 = nombreAdjunto_2;
    }

    public String getNombreAdjunto_3() {
        return nombreAdjunto_3;
    }

    public void setNombreAdjunto_3(String nombreAdjunto_3) {
        this.nombreAdjunto_3 = nombreAdjunto_3;
    }

    public String getNombreAdjunto_4() {
        return nombreAdjunto_4;
    }

    public void setNombreAdjunto_4(String nombreAdjunto_4) {
        this.nombreAdjunto_4 = nombreAdjunto_4;
    }

    public String getNombreAdjunto_5() {
        return nombreAdjunto_5;
    }

    public void setNombreAdjunto_5(String nombreAdjunto_5) {
        this.nombreAdjunto_5 = nombreAdjunto_5;
    }


    public byte[] getAdjunto_1() {
        return adjunto_1;
    }

    public void setAdjunto_1(byte[] adjunto_1) {
        this.adjunto_1 = adjunto_1;
    }

    public byte[] getAdjunto_2() {
        return adjunto_2;
    }

    public void setAdjunto_2(byte[] adjunto_2) {
        this.adjunto_2 = adjunto_2;
    }

    public byte[] getAdjunto_3() {
        return adjunto_3;
    }

    public void setAdjunto_3(byte[] adjunto_3) {
        this.adjunto_3 = adjunto_3;
    }

    public byte[] getAdjunto_4() {
        return adjunto_4;
    }

    public void setAdjunto_4(byte[] adjunto_4) {
        this.adjunto_4 = adjunto_4;
    }

    public byte[] getAdjunto_5() {
        return adjunto_5;
    }

    public void setAdjunto_5(byte[] adjunto_5) {
        this.adjunto_5 = adjunto_5;
    }

    public String getFileRuta() {
        return fileRuta;
    }

    public void setFileRuta(String fileRuta) {
        this.fileRuta = fileRuta;
    }

    public String getCoTipoEmision() {
        return null;
    }

    public void setCoTipoEmision(String value) {

    }

    @Override
    public void setInHabilitado(Integer inHabilitado) {

    }

	public Date getResponseTime() {
		return responseTime;
	}

	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}
}
