//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 06:45:22 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.request;

import org.hibernate.validator.constraints.NotBlank;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "value", "name"
})
public class Parameter {
    public static final String DECLARAR = "declareSunat";
    public static final String DECLARAR_DIRECT = "declareDirectSunat";
    public static final String PUBLICAR = "publish";
    public static final String OUTPUT = "output";
    public static final String ID_EMISOR = "idEmisor";
    public static final String CORREO_EMISOR= "correoEmisor";
    public static final String CORREO_ADQUIRIENTE= "correoAdquiriente";
    public static final String ADQUIRIENTE_VISUALIZA= "adquirienteVisualiza";
    public static final String CONTENIDO = "contenido";
    public static final String ARCHIVO = "archivo";
    public static final String VERSION = "version";
    public static final String ID_ACCION = "idAccion";
    public static final String TIPO_ARCHIVO = "tipoArchivo";
    public static final String TO_STRING = "toString";
    public static final String ID_ADQUIRIENTE = "idAdquiriente";
    public static final String FECHA_FIRMA_INICIO = "fechaFirmaInicio";
    public static final String FECHA_FIRMA_FIN = "fechaFirmaFin";
    public static final String NUMERO_TICKET = "numeroTicket";
    public static final String TIPO_DOCUMENTO = "tipoDocumento";
    public static final String SERIE_GRUPO_DOCUMENTO = "serieGrupoDocumento";
    public static final String NUMERO_CORRELATIVO_INICIO = "numeroCorrelativoInicio";
    public static final String NUMERO_CORRELATIVO_FIN = "numeroCorrelativoFin";
    public static final String ESTADO_DOCUMENTO = "estadoDocumento";
    public static final String ESTADO_SUNAT = "estadoSunat";
    public static final String ORIGEN = "origen";
    public static final String CORRELATIVO_EXCLUIR = "correlativoExcluir";
    public static final String CO_TIPO_EMISION = "coTipoEmision";


    @XmlAttribute(required = true)
    @NotBlank
    protected String name;

    @XmlAttribute(required = true)
    @NotBlank
    protected String value;

    public Parameter() {
    }

    public Parameter(String name, String value) {
        this.name = name;
        this.value = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
