//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 06:45:22 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.request;

import org.hibernate.validator.constraints.NotEmpty;

import com.axteroid.ose.server.ubl20.gateway.CmdSignBatch;

import javax.validation.Valid;
import javax.xml.bind.annotation.*;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "SignBatchCmd")
public class SignBatchCmd extends ActionImpl {

    @XmlAttribute(name = "declare-sunat", required = false)
    protected String declareSunat = "0";

    @XmlAttribute(required = false)
    protected String publish = "0";

    @XmlAttribute(required = false)
    protected String output = "";

    @Override
    public String getResult() {
        return output;
    }

    @XmlElement(name = "parameters", nillable = true)
    @NotEmpty(message = "7027")
    @Valid
    protected List<Parameter> parameters;

    public SignBatchCmd() {
    }

    public List<Parameter> getParameters() {
        return parameters;
    }

    public void setParameters(List<Parameter> parameters) {
        this.parameters = parameters;
    }

    public String getDeclareSunat() {
        return declareSunat;
    }

    public void setDeclareSunat(String declareSunat) {
        this.declareSunat = declareSunat;
    }

    public String getPublish() {
        return publish;
    }

    public void setPublish(String publish) {
        this.publish = publish;
    }

    public Class getInterfaceValidation(){
        return CmdSignBatch.class;
    }

    public String getOutput() {
        return output;
    }

    public void setOutput(String output) {
        this.output = output;
    }
}
