//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 06:45:22 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.request;

import java.util.List;

import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.hibernate.validator.constraints.NotEmpty;

import com.axteroid.ose.server.ubl20.gateway.CmdSignOnLine;
import com.axteroid.ose.server.ubl20.gateway.batch.EPercepcionCliente;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(propOrder = {
        "parameters",
        "documentos"
})
@XmlRootElement(name = "SignOnLinePerceptionCmd")
public class SignOnLinePerceptionCmd extends ActionImpl {
    @XmlAttribute(name = "declare-sunat", required = false)
    protected String declareSunat = "0";
    @XmlAttribute(name = "declare-direct-sunat", required = false)
    protected String declareDirectSunat = "0";
    @XmlAttribute(required = false)
    protected String publish = "0";
    @XmlAttribute(required = false)
    protected String output = "";
    @XmlElement(name = "documento", nillable = true)
    @NotEmpty(groups = CmdSignOnLine.class,message = "7165")
    @Valid
    List<EPercepcionCliente> documentos;

    public SignOnLinePerceptionCmd() {
    }

    @XmlElement(name = "parameter", nillable = true)
    @NotEmpty(message = "7027")
    List<Parameter> parameters;

    @Override
    public String getResult() {
        return output;
    }

    public List<Parameter> getParameters() {
        return parameters;
    }

    public void setParameters(List<Parameter> parameters) {
        this.parameters = parameters;
    }

    public String getDeclareSunat() {
        return declareSunat;
    }

    public void setDeclareSunat(String declareSunat) {
        this.declareSunat = declareSunat;
    }

    public String getPublish() {
        return publish;
    }

    public String getOutput() {
        return output;
    }

    public void setOutput(String output) {
        this.output = output;
    }

    public void setPublish(String publish) {
        this.publish = publish;
    }

    public List<EPercepcionCliente> getDocumentos() {
        return documentos;
    }

    public void setDocumentos(List<EPercepcionCliente> documentos) {
        this.documentos = documentos;
    }

    public String getDeclareDirectSunat() {
        return declareDirectSunat;
    }

    public void setDeclareDirectSunat(String declareDirectSunat) {
        this.declareDirectSunat = declareDirectSunat;
    }
}
