//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 06:45:22 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.request;

import javax.xml.bind.annotation.*;

import com.axteroid.ose.server.ubl20.gateway.batch.EResumenCliente;

import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = {
        "parameters",
        "documentos"
})
@XmlRootElement(name = "SignOnLineSummaryCmd")
public class SignOnLineSummaryCmd extends  ActionImpl  {

    @XmlAttribute(name = "declare-sunat", required = false)
    protected String declareSunat="0" ;

    @XmlAttribute(required = false)
    protected String replicate="0" ;

    @XmlAttribute(required = false)
    protected String output = "";

    @XmlElement(name = "documento",nillable = true)
    List<EResumenCliente> documentos;

    @XmlElement(name = "parameter",nillable = true)
    List<Parameter> parameters;

    @Override
    public String getResult() {
        return output;
    }

    public List<Parameter> getParameters() {
        return parameters;
    }

    public void setParameters(List<Parameter> parameters) {
        this.parameters = parameters;
    }

    public SignOnLineSummaryCmd() {
    }

    public String getDeclareSunat() {
        return declareSunat;
    }

    public void setDeclareSunat(String declareSunat) {
        this.declareSunat = declareSunat;
    }

    public String getPublish() {
        return replicate;
    }

    public void setReplicate(String replicate) {
        this.replicate = replicate;
    }

    public List<EResumenCliente> getDocumentos() {
        return documentos;
    }

    public void setDocumentos(List<EResumenCliente> documentos) {
        this.documentos = documentos;
    }

    @Override
    public String getDeclareDirectSunat() {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }




}
