//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 06:45:22 PM COT 
//


package com.axteroid.ose.server.ubl20.gateway.request;

import javax.xml.bind.annotation.*;

import com.axteroid.ose.server.ubl20.gateway.batch.EResumenCliente;

import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(propOrder = {
        "parameters",
        "documentos"
})
@XmlRootElement(name = "SunatOnLineSummaryCmd")
public class SunatOnLineSummaryCmd extends ActionImpl {

    @XmlAttribute(name = "declare-sunat", required = false)
    protected String declareSunat = "1";

    @XmlAttribute(required = false)
    protected String publish = "1";

    @XmlAttribute(required = false)
    protected String output = "";

    @XmlElement(name = "documento", nillable = true)
    List<EResumenCliente> documentos;

    @Override
    public String getResult() {
        return output;
    }

    public SunatOnLineSummaryCmd() {
    }

    @XmlElement(name = "parameter", nillable = true)
    List<Parameter> parameters;

    public List<Parameter> getParameters() {
        return parameters;
    }

    public void setParameters(List<Parameter> parameters) {
        this.parameters = parameters;
    }

    public String getDeclareSunat() {
        return declareSunat;
    }


    public String getPublish() {
        return publish;
    }


    public List<EResumenCliente> getDocumentos() {
        return documentos;
    }

    public void setDocumentos(List<EResumenCliente> documentos) {
        this.documentos = documentos;
    }

    public void setDeclareSunat(String declareSunat) {
        this.declareSunat = declareSunat;
    }


    public void setPublish(String publish) {
        this.publish = publish;
    }

    @Override
    public String getDeclareDirectSunat() {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }
}
